apiVersion: v1
kind: Service
metadata:
  name: fundamental-analysis-service
spec:
  selector:
    app: fundamental-analysis-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
